#
# Makefile for the Linux Wireless network device drivers.
#
#
obj-$(CPTCFG_WLAN_VENDOR_INTEL) += intel/

#obj-$(CONFIG_HERMES)		+= orinoco/
#
#obj-$(CPTCFG_AIRO)		+= airo.o
#obj-$(CPTCFG_AIRO_CS)		+= airo_cs.o airo.o
#
#obj-$(CPTCFG_ATMEL)             += atmel.o
#obj-$(CPTCFG_PCI_ATMEL)         += atmel_pci.o 
#obj-$(CPTCFG_PCMCIA_ATMEL)      += atmel_cs.o
#
#obj-$(CPTCFG_AT76C50X_USB)      += at76c50x-usb.o
#
#obj-$(CPTCFG_PRISM54)		+= prism54/
#
#obj-$(CONFIG_HOSTAP)		+= hostap/
#obj-$(CONFIG_B43)		+= b43/
#obj-$(CONFIG_B43LEGACY)		+= b43legacy/
#obj-$(CONFIG_ZD1211RW)		+= zd1211rw/
obj-$(CPTCFG_WLAN)		+= realtek/

# 16-bit wireless PCMCIA client drivers
#obj-$(CPTCFG_PCMCIA_RAYCS)	+= ray_cs.o
#obj-$(CPTCFG_PCMCIA_WL3501)	+= wl3501_cs.o
#
#obj-$(CPTCFG_USB_NET_RNDIS_WLAN)	+= rndis_wlan.o
#
#obj-$(CPTCFG_USB_ZD1201)	+= zd1201.o
#obj-$(CONFIG_LIBERTAS)		+= libertas/
#
#obj-$(CPTCFG_LIBERTAS_THINFIRM)	+= libertas_tf/
#
#obj-$(CPTCFG_ADM8211)	+= adm8211.o
#
#obj-$(CPTCFG_MWL8K)	+= mwl8k.o

#obj-$(CONFIG_RT2X00)	+= rt2x00/
#
#obj-$(CONFIG_WL_MEDIATEK)	+= mediatek/
#
#obj-$(CONFIG_P54_COMMON)	+= p54/
#
#obj-$(CONFIG_ATH_CARDS)		+= ath/

obj-$(CPTCFG_MAC80211_HWSIM)	+= mac80211_hwsim.o
#
#obj-$(CONFIG_WL_TI)	+= ti/
#
#obj-$(CONFIG_MWIFIEX)	+= mwifiex/
#
#obj-$(CONFIG_BRCMFMAC)	+= brcm80211/
#obj-$(CONFIG_BRCMSMAC)	+= brcm80211/
#
#obj-$(CONFIG_CW1200)	+= cw1200/
#obj-$(CONFIG_RSI_91X)	+= rsi/
